version: "3"
services:
  client:
    container_name: url_shoretn_client
    build: ./client-vue
    ports:
      - "3000:3000"
    depends_on:
      - "api"

  api:
    container_name: url_shoretn_api
    build: ./backend-node
    ports:
      - "8000:8000"
    depends_on:
      - "mongodb"

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - apiDB:/data/db

volumes:
  apiDB:
